nelmio_api_doc:
    documentation:
        info:
            title: Ordering API Test
            description: Ordering API Test
            version: 1.0.0
    areas:
        path_patterns:
            - ^/v1(?!/doc$) # Accepts routes under /v1 except /v1/doc
